### ISSUE TITLE
Enable frappe_paystack to collect payments via webform and payment links in payment request.

### ISSUE THREAD

**Issue by obiorah** [mymi14s/frappe_paystack#1]
ERPnext has various provisions for collecting payments from third parties. Frappe_paystack is presently confined to e-commerce in erpnext. This feature request seeks an extension of scope to accommodate two use cases.

1. ### Collection of payments through web forms: One scenario is the student applicant webform in the Education domain. Here, an applicant seeking admission completes the webform and makes payment thereafter. Currently, frappe-paystack allows the applicant reach the checkout page and then throws an error... An error occurred with your payment.
The app should be extended to take the customer to the paystack payment popup/page where card/ussd/bank transfer mode is selected and transaction is completed. This will enable erpnext offer its full capacilty to users. 
This feature will be relevant in other domains like health (patients to pay), non-profits (collect donations) etc.

2.   ### Collection of payments from customers via payment urls or links sent via email vis the payment request doctype: One scenario would also be in the Education domain where fees are scheduled via the fee schedule doctype which send payment request via email containing a payment link. 
Currently the payment link sent takes the customer to the checkout page which still throws the same error as above.
This feature would also be relevant for companies processing payments for their customers.

Frappe_paystack
![paystack screenshots 3](https://user-images.githubusercontent.com/51679105/160246658-38aaf5de-5c5e-4667-8275-cb4b083dbc03.jpg)
![paystack screenshots 4](https://user-images.githubusercontent.com/51679105/160246666-36b111c6-8b16-48fa-bb52-795758cd925a.jpg)

**Comment by tjomtek** [comment]
Hi Any updates on this request ?

**Comment by mymi14s** [comment]
The integration works fine out of the box, if extra feature is needed, a feature request should be raised.
